from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, EmailStr


class UserBase(BaseModel):
    username : str  = Field(min_length=1, max_length=50)
    email : EmailStr = Field(max_length = 120)
    # No need to put min_length in email because EmailStr already validates that for us 

class UserCreate(UserBase):
    password : str = Field(min_length= 8)  # Here we add a field for passwords and then we enforce a minimum of 8 characters for the password


class UserResponsePublic(BaseModel):  # Now we inherit from BaseModel instead of UserBase, because we don't want to leak the user email, that is gotten when we inherit from UserBase, that's a privacy concern

    model_config = ConfigDict(from_attributes=True)
    id: int 
    username : str  = Field(min_length=1, max_length=50)
    image_file : str | None
    image_path : str

# We also create two responses instead of one, one for public and the other for private. The private would be used internally while the public would be shown to other users when they check 
# But as for the UserCreate, it still inherits from UserBase, because when creating a user, an email, username and password is required
class UserResponsePrivate(UserResponsePublic):
    email : EmailStr = Field(max_length = 120)

    # The UserResponsePrivate schema inherits from UserResponsePublic because we UserResponsePublic has all the required fields required for a response , and then we add email to it to the private one 


# The Token schema is a schema used to check if the token comes in the required fields 
class Token(BaseModel):
    access_token : str
    token_type : str


class UserUpdate(BaseModel): 
    username : str | None  = Field(min_length=1, max_length=50, default= None)
    email : EmailStr | None = Field(max_length = 120, default= None)
    # No need to put min_length in email because EmailStr already validates that for us 
    image_file : str | None  = Field(min_length=1, max_length=200
    , default= None)

    # Wanted to include a property decorator to create image_path and inside the image_path, will do if image_file is None and so onc, but I didn't know how to complete the logic and I think exclude_unset = True, would take care of the None and give back the old value so that issue should be taken care of 


class PostBase(BaseModel):
    title: str = Field(min_length=1,max_length=100,description="Title of post(Min of 1 letter and and maximum of 100)")
    content: str = Field(min_length=1)
    # author: str = Field(min_length=1,max_length=50,description="Author of post(Min of 1 letter and and maximum of 100)")

    # Removed or commented line 23 because we can get the author from the UserResponse class, which shows the author and everything about them.
    # Recall that we did User.posts = Post.author (ln 20 in schemas.py)

class PostResponse(PostBase):
    model_config = ConfigDict(from_attributes=True)
    
    id :int 
    user_id : int 
    date_posted :datetime  # Using a type hint of datetime automatically serializes the date into a ISO8601 format instead of str , that we won't know it is a datetime object 
    author : UserResponsePublic


class PostCreate(PostBase):
    pass
    # user_id : int # Before , to create posts, we would require title and content(which were inherited from PostBase), then we would include a user_id , for the id of the user , the post is going to. This is wrong though because , a user could pretend to be another user by put an id which is not theirs.
    # To fix this issue, instead of asking the user to put in a user id, we check for the user_id ourselves, we do this by checking for the user access token and extracting the id from it.
    # if the token was generated by user, then we should be able to extract it, else when extracting and we have error then it is not ours or in the event there is no token , then the user is not authenticated with us


# Now we are creating a schema for updating a resource

# We have two types of update : Put (Full update) and Patch (Partial Update)
# For full update, we can just re-use our PostCreate schema as we would replace everything inside 
# For partial update, we would have to create another schema that uses optional fields instead of PostCreate that the Fields must contain something

# NOTE THAT PostUpdate inherits from BaseModel and not from PostBase, if we inherited from  PostBase, we would have some issues as we would inherit title and content that we want to change from PostBase but the title and content would have the type hint of str but since we are changing things partially, we would want our type hint to be str or None, as a field can be filled while the other remains None.
# But we can't change the inherited type hint from PostBase, so we create another class and create title and content attributes with the type hint str | None 


class PostUpdate(BaseModel):
    title: str | None= Field(default=None, min_length=1,max_length=100,description="Title of post(Min of 1 letter and and maximum of 100)")
    content: str | None = Field(default=None, min_length=1)


# I think that PostUpdate would be same with PostCreate, but for PostUpdate PATCH it would have an None type hint too for optional values and we must have a default value in case that field is not filled in 
# While we can just use PostCreate for PostUpdate PUT CRUD
# We would implement cascade delete, which is when we delete a user, we delete all his posts along with him


# We also didn't include user_id in the PostUpdate, this is because it is considered wrong to change ownership of an object through a PATCH CRUD. Example : Changing ownership of a post through a PATCH is considered wrong

